[package]
name = "vmod_fileserver"
version = "0.1.0"
rust-version = "1.90.0"
edition = "2024"
license = "BSD-3-Clause"
publish = false

[features]
default = ["autoindex"]
autoindex = ["dep:serde", "dep:serde_json", "dep:yaml_serde", "chrono/serde"]

[dependencies]
chrono = "0.4.45"
libc = "0.2"
openat = "0.1.21"
varnish = { version = "0.7.0", features = ["ffi"] }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
yaml_serde = { version = "0.10", optional = true }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unused_qualifications = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
